version: '3.9'
services:
  mongoDB:
    image: 'mongodb/mongodb-community-server:6.0-ubi8'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - ${DB_PORT:-1521}:1521
      - ${DB_PORT2:-5500}:5500
    networks: 
      - app
  server:
    build:
      context: ./server/
      dockerfile: ../.dock/local/Dockerfile.SERVER
    image: ${COMPOSE_PROJECT_NAME:?err}_server
    environment:
      - CONN_STR=mongodb://user:pass@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongoDB
    networks:
      - app
  client:
    build:
      context: ./client/
      dockerfile: ../.dock/local/Dockerfile.CLIENT
    image: ${COMPOSE_PROJECT_NAME:?err}_client
    networks:
      - app
networks:
  app:
    attachable: true