version: '3.9'
services:
  client:
    stdin_open: true
    user: root
    build:
      context: ./client/
      dockerfile: ../.dock/local/Dockerfile.CLIENT
    image: ${COMPOSE_PROJECT_NAME:?err}_client
    volumes:
      - ./client:/usr/local/app
      - exclude-client:/usr/local/app/node_modules:rw
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - ./.conf/${NODE_ENV:-err}.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - DISABLE_ESLINT_PLUGIN=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_PUBLIC_URL=${PUBLIC_URL}
      - REACT_APP_URL_PREFIX=${URL_PREFIX}
      - PORT=${CLIENT_PORT}
    command: ['start']
  server:
    user: root
    build:
      context: ./server/
      dockerfile: ../.dock/local/Dockerfile.SERVER
    image: ${COMPOSE_PROJECT_NAME:?err}_server
    volumes:
      - ./server:/usr/src/app
      - exclude-server:/usr/src/app/node_modules:rw
    ports:
      - 3100:3100
    env_file:
      - ./.conf/secrets.env
      - ./.conf/${NODE_ENV:?err}.env
    command: ['start']
volumes:
  exclude-client:
  exclude-server: